# Configuração do Banco de Dados Oracle
spring.datasource.url=jdbc:oracle:thin:@oracle.fiap.com.br:1521:orcl
spring.datasource.username=rm560088
spring.datasource.password=061005
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# Configurações de Pool de Conexão
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.connection-timeout=30000

# Logging
logging.level.org.springframework.jdbc=DEBUG
logging.level.br.fiap=DEBUG

